name: 托管
on:
  workflow_dispatch:
  schedule:
     - cron:  '0 3,12,20 * * *'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: npm install
        run: |
          npm install @octokit/core
      - name: 更新
        env:
          TOKEN: ${{ secrets.TOKEN }}
        run: node Src/action.mjs
        
