name: 托管
on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: npm install
        run: |
          npm install @octokit/core
      - name: 更新
        run: node Src/action.mjs
